id: rapport-vins
namespace: traitement.vins

inputs:
  - id: github_url
    type: STRING
    defaults: https://github.com/Florian-Biggio/Kestra-project/

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone
        type: io.kestra.plugin.git.Clone
        url: "{{ inputs.github_url }}"

      - id: analyse_deduplication
        type: io.kestra.plugin.jdbc.duckdb.Query
        inputFiles:
          erp.xlsx: "{{ workingDir }}/data/Fichier_erp.xlsx"
          web.xlsx: "{{ workingDir }}/data/Fichier_web.xlsx"
          liaison.xlsx: "{{ workingDir }}/data/fichier_liaison.xlsx"
        sql: "{{ workingDir }}/sql/deduplication_merge.sql"
        outputFiles:
          - "{{ workingDir }}/output/final_merge.csv"
        fetchType: STORE

      - id: lancer-script-python
        type: io.kestra.plugin.scripts.python.Commands
        commands:
          - python scripts/traitement_vins.py
        beforeCommands:
          - pip install pandas openpyxl scipy kestra # Install dependencies if needed
        outputFiles:
          - "output/*.csv"
          - "output/*.xlsx"
        warningOnStdErr:
          False
        taskRunner:
          type: io.kestra.plugin.core.runner.Process

triggers:
  - id: planification_mensuelle
    type: io.kestra.plugin.core.trigger.Schedule
    timezone: Europe/Paris
    cron: "0 9 15 * *"  # Trigger on the 15th of every month at 9 AM 
    recoverMissedSchedules: LAST
