id: rapport-vins
namespace: traitement.vins

tasks:
  - id: lancer-script-python
    type: io.kestra.plugin.scripts.python.Commands
    warningOnStdErr: false
    namespaceFiles:
      enabled: true
    commands:
      - pip install pandas openpyxl scipy kestra # Ensure pandas is available
      - python traitement_vins.py
    beforeCommands:
      - pip install pandas openpyxl # Install dependencies if needed
    outputFiles:
      - "output/*.csv"
      - "output/*.xlsx"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process

triggers:
  - id: planification_mensuelle
    type: io.kestra.plugin.core.trigger.Schedule
    timezone: Europe/Paris
    cron: "0 9 15 * *"  # Trigger on the 15th of every month at 9 AM 
    recoverMissedSchedules: LAST